services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ledger2
      POSTGRES_USER: ledger2
      POSTGRES_PASSWORD: ledger2
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
