spring.application.name=ledger2

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/ledger2
spring.datasource.username=ledger2
spring.datasource.password=ledger2

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
